version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    $urlCurrent = "https://download.microsoft.com/download/4/0/9/40920432-3302-47a8-b13c-bbc4848ad114/dotnet-sdk-2.1.302-win-x64.zip"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"

    mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null

    $tempFileCurrent = [System.IO.Path]::GetTempFileName()

    (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)

    Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)

    $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
build_script:
- ps: >-
    dotnet --version

    dotnet publish -c Release -r win-x64
    
    dotnet publish -c Release -r linux-x64
    
    dotnet publish -c Release -r osx-x64

    7z a ryujinx-$env:APPVEYOR_BUILD_VERSION-win_x64.zip $env:APPVEYOR_BUILD_FOLDER\Ryujinx\bin\Release\netcoreapp2.1\win-x64\publish\

    7z a ryujinx-$env:APPVEYOR_BUILD_VERSION-linux_x64.zip $env:APPVEYOR_BUILD_FOLDER\Ryujinx\bin\Release\netcoreapp2.1\linux-x64\publish\

    7z a ryujinx-$env:APPVEYOR_BUILD_VERSION-osx_x64.zip $env:APPVEYOR_BUILD_FOLDER\Ryujinx\bin\Release\netcoreapp2.1\osx-x64\publish\

artifacts:
- path: ryujinx-%APPVEYOR_BUILD_VERSION%.zip
